# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b99ba758acf42a6123d87abca95f8576c79c91d4be84906f100532ee0c65d5c69601ec56d91c14aa1a2a040b3260c4725a7bd32554bc5ec5b0e7a5b12dbaca6

test:
  secret_key_base: e0d4f4dec024a6a17c825d9b47a392e774b20f7f8fe3e2a5d88f61880331ff6aafcc5ddaaa1056cc36c02ac67af9a7e51e19dbbd05e244eec777d2d59d58a794

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
